defmodule Adyen.Payments.PaymentRequest do
  @moduledoc """
  Provides struct and type for a PaymentRequest
  """

  @type t :: %__MODULE__{
          accountInfo: Adyen.Payments.AccountInfo.t() | nil,
          additionalAmount: Adyen.Payments.Amount.t() | nil,
          additionalData: map | nil,
          amount: Adyen.Payments.Amount.t(),
          applicationInfo: Adyen.Payments.ApplicationInfo.t() | nil,
          bankAccount: Adyen.Payments.BankAccount.t() | nil,
          billingAddress: Adyen.Payments.Address.t() | nil,
          browserInfo: Adyen.Payments.BrowserInfo.t() | nil,
          captureDelayHours: integer | nil,
          card: Adyen.Payments.Card.t() | nil,
          dateOfBirth: Date.t() | nil,
          dccQuote: Adyen.Payments.ForexQuote.t() | nil,
          deliveryAddress: Adyen.Payments.Address.t() | nil,
          deliveryDate: DateTime.t() | nil,
          deviceFingerprint: String.t() | nil,
          entityType: String.t() | nil,
          fraudOffset: integer | nil,
          fundDestination: Adyen.Payments.FundDestination.t() | nil,
          fundSource: Adyen.Payments.FundSource.t() | nil,
          fundingSource: String.t() | nil,
          installments: Adyen.Payments.Installments.t() | nil,
          localizedShopperStatement: map | nil,
          mandate: Adyen.Payments.Mandate.t() | nil,
          mcc: String.t() | nil,
          merchantAccount: String.t(),
          merchantOrderReference: String.t() | nil,
          merchantRiskIndicator: Adyen.Payments.MerchantRiskIndicator.t() | nil,
          metadata: map | nil,
          mpiData: Adyen.Payments.ThreeDSecureData.t() | nil,
          nationality: String.t() | nil,
          orderReference: String.t() | nil,
          platformChargebackLogic: Adyen.Payments.PlatformChargebackLogic.t() | nil,
          recurring: Adyen.Payments.Recurring.t() | nil,
          recurringProcessingModel: String.t() | nil,
          reference: String.t(),
          secureRemoteCommerceCheckoutData:
            Adyen.Payments.SecureRemoteCommerceCheckoutData.t() | nil,
          selectedBrand: String.t() | nil,
          selectedRecurringDetailReference: String.t() | nil,
          sessionId: String.t() | nil,
          shopperEmail: String.t() | nil,
          shopperIP: String.t() | nil,
          shopperInteraction: String.t() | nil,
          shopperLocale: String.t() | nil,
          shopperName: Adyen.Payments.Name.t() | nil,
          shopperReference: String.t() | nil,
          shopperStatement: String.t() | nil,
          socialSecurityNumber: String.t() | nil,
          splits: [Adyen.Payments.Split.t()] | nil,
          store: String.t() | nil,
          telephoneNumber: String.t() | nil,
          threeDS2RequestData: Adyen.Payments.ThreeDs2RequestData.t() | nil,
          threeDSAuthenticationOnly: boolean | nil,
          totalsGroup: String.t() | nil,
          trustedShopper: boolean | nil
        }

  defstruct [
    :accountInfo,
    :additionalAmount,
    :additionalData,
    :amount,
    :applicationInfo,
    :bankAccount,
    :billingAddress,
    :browserInfo,
    :captureDelayHours,
    :card,
    :dateOfBirth,
    :dccQuote,
    :deliveryAddress,
    :deliveryDate,
    :deviceFingerprint,
    :entityType,
    :fraudOffset,
    :fundDestination,
    :fundSource,
    :fundingSource,
    :installments,
    :localizedShopperStatement,
    :mandate,
    :mcc,
    :merchantAccount,
    :merchantOrderReference,
    :merchantRiskIndicator,
    :metadata,
    :mpiData,
    :nationality,
    :orderReference,
    :platformChargebackLogic,
    :recurring,
    :recurringProcessingModel,
    :reference,
    :secureRemoteCommerceCheckoutData,
    :selectedBrand,
    :selectedRecurringDetailReference,
    :sessionId,
    :shopperEmail,
    :shopperIP,
    :shopperInteraction,
    :shopperLocale,
    :shopperName,
    :shopperReference,
    :shopperStatement,
    :socialSecurityNumber,
    :splits,
    :store,
    :telephoneNumber,
    :threeDS2RequestData,
    :threeDSAuthenticationOnly,
    :totalsGroup,
    :trustedShopper
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accountInfo: {Adyen.Payments.AccountInfo, :t},
      additionalAmount: {Adyen.Payments.Amount, :t},
      additionalData: :map,
      amount: {Adyen.Payments.Amount, :t},
      applicationInfo: {Adyen.Payments.ApplicationInfo, :t},
      bankAccount: {Adyen.Payments.BankAccount, :t},
      billingAddress: {Adyen.Payments.Address, :t},
      browserInfo: {Adyen.Payments.BrowserInfo, :t},
      captureDelayHours: {:integer, "int32"},
      card: {Adyen.Payments.Card, :t},
      dateOfBirth: {:string, "date"},
      dccQuote: {Adyen.Payments.ForexQuote, :t},
      deliveryAddress: {Adyen.Payments.Address, :t},
      deliveryDate: {:string, "date-time"},
      deviceFingerprint: :string,
      entityType: {:enum, ["NaturalPerson", "CompanyName"]},
      fraudOffset: {:integer, "int32"},
      fundDestination: {Adyen.Payments.FundDestination, :t},
      fundSource: {Adyen.Payments.FundSource, :t},
      fundingSource: {:enum, ["credit", "debit", "prepaid"]},
      installments: {Adyen.Payments.Installments, :t},
      localizedShopperStatement: :map,
      mandate: {Adyen.Payments.Mandate, :t},
      mcc: :string,
      merchantAccount: :string,
      merchantOrderReference: :string,
      merchantRiskIndicator: {Adyen.Payments.MerchantRiskIndicator, :t},
      metadata: :map,
      mpiData: {Adyen.Payments.ThreeDSecureData, :t},
      nationality: :string,
      orderReference: :string,
      platformChargebackLogic: {Adyen.Payments.PlatformChargebackLogic, :t},
      recurring: {Adyen.Payments.Recurring, :t},
      recurringProcessingModel: {:enum, ["CardOnFile", "Subscription", "UnscheduledCardOnFile"]},
      reference: :string,
      secureRemoteCommerceCheckoutData: {Adyen.Payments.SecureRemoteCommerceCheckoutData, :t},
      selectedBrand: :string,
      selectedRecurringDetailReference: :string,
      sessionId: :string,
      shopperEmail: :string,
      shopperIP: :string,
      shopperInteraction: {:enum, ["Ecommerce", "ContAuth", "Moto", "POS"]},
      shopperLocale: :string,
      shopperName: {Adyen.Payments.Name, :t},
      shopperReference: :string,
      shopperStatement: :string,
      socialSecurityNumber: :string,
      splits: [{Adyen.Payments.Split, :t}],
      store: :string,
      telephoneNumber: :string,
      threeDS2RequestData: {Adyen.Payments.ThreeDs2RequestData, :t},
      threeDSAuthenticationOnly: :boolean,
      totalsGroup: :string,
      trustedShopper: :boolean
    ]
  end
end
