defmodule Adyen.Management.V1.PaymentMethod do
  @moduledoc """
  Provides struct and type for a PaymentMethod
  """

  @type t :: %__MODULE__{
          accel: Adyen.Management.V1.AccelInfo.t() | nil,
          affirm: Adyen.Management.V1.AffirmInfo.t() | nil,
          afterpayTouch: Adyen.Management.V1.AfterpayTouchInfo.t() | nil,
          alipayPlus: Adyen.Management.V1.AlipayPlusInfo.t() | nil,
          allowed: boolean | nil,
          amex: Adyen.Management.V1.AmexInfo.t() | nil,
          applePay: Adyen.Management.V1.ApplePayInfo.t() | nil,
          bcmc: Adyen.Management.V1.BcmcInfo.t() | nil,
          businessLineId: String.t() | nil,
          cartesBancaires: Adyen.Management.V1.CartesBancairesInfo.t() | nil,
          clearpay: Adyen.Management.V1.ClearpayInfo.t() | nil,
          countries: [String.t()] | nil,
          cup: Adyen.Management.V1.GenericPmWithTdiInfo.t() | nil,
          currencies: [String.t()] | nil,
          customRoutingFlags: [String.t()] | nil,
          diners: Adyen.Management.V1.DinersInfo.t() | nil,
          discover: Adyen.Management.V1.GenericPmWithTdiInfo.t() | nil,
          eft_directdebit_CA: Adyen.Management.V1.GenericPmWithTdiInfo.t() | nil,
          eftpos_australia: Adyen.Management.V1.GenericPmWithTdiInfo.t() | nil,
          enabled: boolean | nil,
          girocard: Adyen.Management.V1.GenericPmWithTdiInfo.t() | nil,
          givex: Adyen.Management.V1.GivexInfo.t() | nil,
          googlePay: Adyen.Management.V1.GooglePayInfo.t() | nil,
          id: String.t(),
          ideal: Adyen.Management.V1.GenericPmWithTdiInfo.t() | nil,
          interac_card: Adyen.Management.V1.GenericPmWithTdiInfo.t() | nil,
          jcb: Adyen.Management.V1.JCBInfo.t() | nil,
          klarna: Adyen.Management.V1.KlarnaInfo.t() | nil,
          maestro: Adyen.Management.V1.GenericPmWithTdiInfo.t() | nil,
          maestro_usa: Adyen.Management.V1.GenericPmWithTdiInfo.t() | nil,
          mc: Adyen.Management.V1.GenericPmWithTdiInfo.t() | nil,
          mealVoucher_FR: Adyen.Management.V1.MealVoucherFRInfo.t() | nil,
          nyce: Adyen.Management.V1.NyceInfo.t() | nil,
          paybybank_plaid: Adyen.Management.V1.PayByBankPlaidInfo.t() | nil,
          payme: Adyen.Management.V1.PayMeInfo.t() | nil,
          paypal: Adyen.Management.V1.PayPalInfo.t() | nil,
          payto: Adyen.Management.V1.PayToInfo.t() | nil,
          pulse: Adyen.Management.V1.PulseInfo.t() | nil,
          reference: String.t() | nil,
          sepadirectdebit: Adyen.Management.V1.SepaDirectDebitInfo.t() | nil,
          shopperInteraction: String.t() | nil,
          sodexo: Adyen.Management.V1.SodexoInfo.t() | nil,
          sofort: Adyen.Management.V1.SofortInfo.t() | nil,
          star: Adyen.Management.V1.StarInfo.t() | nil,
          storeId: String.t() | nil,
          svs: Adyen.Management.V1.SvsInfo.t() | nil,
          swish: Adyen.Management.V1.SwishInfo.t() | nil,
          ticket: Adyen.Management.V1.TicketInfo.t() | nil,
          twint: Adyen.Management.V1.TwintInfo.t() | nil,
          type: String.t() | nil,
          valuelink: Adyen.Management.V1.ValuelinkInfo.t() | nil,
          verificationStatus: String.t() | nil,
          vipps: Adyen.Management.V1.VippsInfo.t() | nil,
          visa: Adyen.Management.V1.GenericPmWithTdiInfo.t() | nil,
          wechatpay: Adyen.Management.V1.WeChatPayInfo.t() | nil,
          wechatpay_pos: Adyen.Management.V1.WeChatPayPosInfo.t() | nil
        }

  defstruct [
    :accel,
    :affirm,
    :afterpayTouch,
    :alipayPlus,
    :allowed,
    :amex,
    :applePay,
    :bcmc,
    :businessLineId,
    :cartesBancaires,
    :clearpay,
    :countries,
    :cup,
    :currencies,
    :customRoutingFlags,
    :diners,
    :discover,
    :eft_directdebit_CA,
    :eftpos_australia,
    :enabled,
    :girocard,
    :givex,
    :googlePay,
    :id,
    :ideal,
    :interac_card,
    :jcb,
    :klarna,
    :maestro,
    :maestro_usa,
    :mc,
    :mealVoucher_FR,
    :nyce,
    :paybybank_plaid,
    :payme,
    :paypal,
    :payto,
    :pulse,
    :reference,
    :sepadirectdebit,
    :shopperInteraction,
    :sodexo,
    :sofort,
    :star,
    :storeId,
    :svs,
    :swish,
    :ticket,
    :twint,
    :type,
    :valuelink,
    :verificationStatus,
    :vipps,
    :visa,
    :wechatpay,
    :wechatpay_pos
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accel: {Adyen.Management.V1.AccelInfo, :t},
      affirm: {Adyen.Management.V1.AffirmInfo, :t},
      afterpayTouch: {Adyen.Management.V1.AfterpayTouchInfo, :t},
      alipayPlus: {Adyen.Management.V1.AlipayPlusInfo, :t},
      allowed: :boolean,
      amex: {Adyen.Management.V1.AmexInfo, :t},
      applePay: {Adyen.Management.V1.ApplePayInfo, :t},
      bcmc: {Adyen.Management.V1.BcmcInfo, :t},
      businessLineId: :string,
      cartesBancaires: {Adyen.Management.V1.CartesBancairesInfo, :t},
      clearpay: {Adyen.Management.V1.ClearpayInfo, :t},
      countries: [:string],
      cup: {Adyen.Management.V1.GenericPmWithTdiInfo, :t},
      currencies: [:string],
      customRoutingFlags: [:string],
      diners: {Adyen.Management.V1.DinersInfo, :t},
      discover: {Adyen.Management.V1.GenericPmWithTdiInfo, :t},
      eft_directdebit_CA: {Adyen.Management.V1.GenericPmWithTdiInfo, :t},
      eftpos_australia: {Adyen.Management.V1.GenericPmWithTdiInfo, :t},
      enabled: :boolean,
      girocard: {Adyen.Management.V1.GenericPmWithTdiInfo, :t},
      givex: {Adyen.Management.V1.GivexInfo, :t},
      googlePay: {Adyen.Management.V1.GooglePayInfo, :t},
      id: :string,
      ideal: {Adyen.Management.V1.GenericPmWithTdiInfo, :t},
      interac_card: {Adyen.Management.V1.GenericPmWithTdiInfo, :t},
      jcb: {Adyen.Management.V1.JCBInfo, :t},
      klarna: {Adyen.Management.V1.KlarnaInfo, :t},
      maestro: {Adyen.Management.V1.GenericPmWithTdiInfo, :t},
      maestro_usa: {Adyen.Management.V1.GenericPmWithTdiInfo, :t},
      mc: {Adyen.Management.V1.GenericPmWithTdiInfo, :t},
      mealVoucher_FR: {Adyen.Management.V1.MealVoucherFRInfo, :t},
      nyce: {Adyen.Management.V1.NyceInfo, :t},
      paybybank_plaid: {Adyen.Management.V1.PayByBankPlaidInfo, :t},
      payme: {Adyen.Management.V1.PayMeInfo, :t},
      paypal: {Adyen.Management.V1.PayPalInfo, :t},
      payto: {Adyen.Management.V1.PayToInfo, :t},
      pulse: {Adyen.Management.V1.PulseInfo, :t},
      reference: :string,
      sepadirectdebit: {Adyen.Management.V1.SepaDirectDebitInfo, :t},
      shopperInteraction: :string,
      sodexo: {Adyen.Management.V1.SodexoInfo, :t},
      sofort: {Adyen.Management.V1.SofortInfo, :t},
      star: {Adyen.Management.V1.StarInfo, :t},
      storeId: :string,
      svs: {Adyen.Management.V1.SvsInfo, :t},
      swish: {Adyen.Management.V1.SwishInfo, :t},
      ticket: {Adyen.Management.V1.TicketInfo, :t},
      twint: {Adyen.Management.V1.TwintInfo, :t},
      type: :string,
      valuelink: {Adyen.Management.V1.ValuelinkInfo, :t},
      verificationStatus: {:enum, ["valid", "pending", "invalid", "rejected"]},
      vipps: {Adyen.Management.V1.VippsInfo, :t},
      visa: {Adyen.Management.V1.GenericPmWithTdiInfo, :t},
      wechatpay: {Adyen.Management.V1.WeChatPayInfo, :t},
      wechatpay_pos: {Adyen.Management.V1.WeChatPayPosInfo, :t}
    ]
  end
end
