defmodule Adyen.Management.PaymentMethod do
  @moduledoc """
  Provides struct and type for a PaymentMethod
  """

  @type t :: %__MODULE__{
          accel: Adyen.Management.AccelInfo.t() | nil,
          affirm: Adyen.Management.AffirmInfo.t() | nil,
          afterpayTouch: Adyen.Management.AfterpayTouchInfo.t() | nil,
          alipayPlus: Adyen.Management.AlipayPlusInfo.t() | nil,
          allowed: boolean | nil,
          amex: Adyen.Management.AmexInfo.t() | nil,
          applePay: Adyen.Management.ApplePayInfo.t() | nil,
          bcmc: Adyen.Management.BcmcInfo.t() | nil,
          businessLineId: String.t() | nil,
          cartesBancaires: Adyen.Management.CartesBancairesInfo.t() | nil,
          clearpay: Adyen.Management.ClearpayInfo.t() | nil,
          countries: [String.t()] | nil,
          cup: Adyen.Management.GenericPmWithTdiInfo.t() | nil,
          currencies: [String.t()] | nil,
          customRoutingFlags: [String.t()] | nil,
          diners: Adyen.Management.DinersInfo.t() | nil,
          discover: Adyen.Management.GenericPmWithTdiInfo.t() | nil,
          eft_directdebit_CA: Adyen.Management.GenericPmWithTdiInfo.t() | nil,
          eftpos_australia: Adyen.Management.GenericPmWithTdiInfo.t() | nil,
          enabled: boolean | nil,
          girocard: Adyen.Management.GenericPmWithTdiInfo.t() | nil,
          givex: Adyen.Management.GivexInfo.t() | nil,
          googlePay: Adyen.Management.GooglePayInfo.t() | nil,
          id: String.t(),
          ideal: Adyen.Management.GenericPmWithTdiInfo.t() | nil,
          interac_card: Adyen.Management.GenericPmWithTdiInfo.t() | nil,
          jcb: Adyen.Management.JCBInfo.t() | nil,
          klarna: Adyen.Management.KlarnaInfo.t() | nil,
          maestro: Adyen.Management.GenericPmWithTdiInfo.t() | nil,
          maestro_usa: Adyen.Management.GenericPmWithTdiInfo.t() | nil,
          mc: Adyen.Management.GenericPmWithTdiInfo.t() | nil,
          mealVoucher_FR: Adyen.Management.MealVoucherFRInfo.t() | nil,
          nyce: Adyen.Management.NyceInfo.t() | nil,
          paybybank_plaid: Adyen.Management.PayByBankPlaidInfo.t() | nil,
          payme: Adyen.Management.PayMeInfo.t() | nil,
          paypal: Adyen.Management.PayPalInfo.t() | nil,
          payto: Adyen.Management.PayToInfo.t() | nil,
          pulse: Adyen.Management.PulseInfo.t() | nil,
          reference: String.t() | nil,
          sepadirectdebit: Adyen.Management.SepaDirectDebitInfo.t() | nil,
          shopperInteraction: String.t() | nil,
          sodexo: Adyen.Management.SodexoInfo.t() | nil,
          sofort: Adyen.Management.SofortInfo.t() | nil,
          star: Adyen.Management.StarInfo.t() | nil,
          storeIds: [String.t()] | nil,
          svs: Adyen.Management.SvsInfo.t() | nil,
          swish: Adyen.Management.SwishInfo.t() | nil,
          ticket: Adyen.Management.TicketInfo.t() | nil,
          twint: Adyen.Management.TwintInfo.t() | nil,
          type: String.t() | nil,
          valuelink: Adyen.Management.ValuelinkInfo.t() | nil,
          verificationStatus: String.t() | nil,
          vipps: Adyen.Management.VippsInfo.t() | nil,
          visa: Adyen.Management.GenericPmWithTdiInfo.t() | nil,
          wechatpay: Adyen.Management.WeChatPayInfo.t() | nil,
          wechatpay_pos: Adyen.Management.WeChatPayPosInfo.t() | nil
        }

  defstruct [
    :accel,
    :affirm,
    :afterpayTouch,
    :alipayPlus,
    :allowed,
    :amex,
    :applePay,
    :bcmc,
    :businessLineId,
    :cartesBancaires,
    :clearpay,
    :countries,
    :cup,
    :currencies,
    :customRoutingFlags,
    :diners,
    :discover,
    :eft_directdebit_CA,
    :eftpos_australia,
    :enabled,
    :girocard,
    :givex,
    :googlePay,
    :id,
    :ideal,
    :interac_card,
    :jcb,
    :klarna,
    :maestro,
    :maestro_usa,
    :mc,
    :mealVoucher_FR,
    :nyce,
    :paybybank_plaid,
    :payme,
    :paypal,
    :payto,
    :pulse,
    :reference,
    :sepadirectdebit,
    :shopperInteraction,
    :sodexo,
    :sofort,
    :star,
    :storeIds,
    :svs,
    :swish,
    :ticket,
    :twint,
    :type,
    :valuelink,
    :verificationStatus,
    :vipps,
    :visa,
    :wechatpay,
    :wechatpay_pos
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accel: {Adyen.Management.AccelInfo, :t},
      affirm: {Adyen.Management.AffirmInfo, :t},
      afterpayTouch: {Adyen.Management.AfterpayTouchInfo, :t},
      alipayPlus: {Adyen.Management.AlipayPlusInfo, :t},
      allowed: :boolean,
      amex: {Adyen.Management.AmexInfo, :t},
      applePay: {Adyen.Management.ApplePayInfo, :t},
      bcmc: {Adyen.Management.BcmcInfo, :t},
      businessLineId: :string,
      cartesBancaires: {Adyen.Management.CartesBancairesInfo, :t},
      clearpay: {Adyen.Management.ClearpayInfo, :t},
      countries: [:string],
      cup: {Adyen.Management.GenericPmWithTdiInfo, :t},
      currencies: [:string],
      customRoutingFlags: [:string],
      diners: {Adyen.Management.DinersInfo, :t},
      discover: {Adyen.Management.GenericPmWithTdiInfo, :t},
      eft_directdebit_CA: {Adyen.Management.GenericPmWithTdiInfo, :t},
      eftpos_australia: {Adyen.Management.GenericPmWithTdiInfo, :t},
      enabled: :boolean,
      girocard: {Adyen.Management.GenericPmWithTdiInfo, :t},
      givex: {Adyen.Management.GivexInfo, :t},
      googlePay: {Adyen.Management.GooglePayInfo, :t},
      id: :string,
      ideal: {Adyen.Management.GenericPmWithTdiInfo, :t},
      interac_card: {Adyen.Management.GenericPmWithTdiInfo, :t},
      jcb: {Adyen.Management.JCBInfo, :t},
      klarna: {Adyen.Management.KlarnaInfo, :t},
      maestro: {Adyen.Management.GenericPmWithTdiInfo, :t},
      maestro_usa: {Adyen.Management.GenericPmWithTdiInfo, :t},
      mc: {Adyen.Management.GenericPmWithTdiInfo, :t},
      mealVoucher_FR: {Adyen.Management.MealVoucherFRInfo, :t},
      nyce: {Adyen.Management.NyceInfo, :t},
      paybybank_plaid: {Adyen.Management.PayByBankPlaidInfo, :t},
      payme: {Adyen.Management.PayMeInfo, :t},
      paypal: {Adyen.Management.PayPalInfo, :t},
      payto: {Adyen.Management.PayToInfo, :t},
      pulse: {Adyen.Management.PulseInfo, :t},
      reference: :string,
      sepadirectdebit: {Adyen.Management.SepaDirectDebitInfo, :t},
      shopperInteraction: :string,
      sodexo: {Adyen.Management.SodexoInfo, :t},
      sofort: {Adyen.Management.SofortInfo, :t},
      star: {Adyen.Management.StarInfo, :t},
      storeIds: [:string],
      svs: {Adyen.Management.SvsInfo, :t},
      swish: {Adyen.Management.SwishInfo, :t},
      ticket: {Adyen.Management.TicketInfo, :t},
      twint: {Adyen.Management.TwintInfo, :t},
      type: :string,
      valuelink: {Adyen.Management.ValuelinkInfo, :t},
      verificationStatus: {:enum, ["valid", "pending", "invalid", "rejected"]},
      vipps: {Adyen.Management.VippsInfo, :t},
      visa: {Adyen.Management.GenericPmWithTdiInfo, :t},
      wechatpay: {Adyen.Management.WeChatPayInfo, :t},
      wechatpay_pos: {Adyen.Management.WeChatPayPosInfo, :t}
    ]
  end
end
