defmodule Adyen.Checkout.CreateCheckoutSessionRequest do
  @moduledoc """
  Provides struct and type for a CreateCheckoutSessionRequest
  """

  alias Adyen.Checkout.AccountInfo
  alias Adyen.Checkout.Amount
  alias Adyen.Checkout.ApplicationInfo
  alias Adyen.Checkout.AuthenticationData
  alias Adyen.Checkout.BillingAddress
  alias Adyen.Checkout.CheckoutSessionThreeDs2RequestData
  alias Adyen.Checkout.Company
  alias Adyen.Checkout.DeliveryAddress
  alias Adyen.Checkout.FundOrigin
  alias Adyen.Checkout.FundRecipient
  alias Adyen.Checkout.LineItem
  alias Adyen.Checkout.Mandate
  alias Adyen.Checkout.PlatformChargebackLogic
  alias Adyen.Checkout.RiskData
  alias Adyen.Checkout.ShopperName
  alias Adyen.Checkout.Split
  alias Adyen.Checkout.ThreeDSecureData

  @type t :: %__MODULE__{
          accountInfo: AccountInfo.t() | nil,
          additionalAmount: Amount.t() | nil,
          additionalData: map | nil,
          allowedPaymentMethods: [String.t()] | nil,
          amount: Amount.t(),
          applicationInfo: ApplicationInfo.t() | nil,
          authenticationData: AuthenticationData.t() | nil,
          billingAddress: BillingAddress.t() | nil,
          blockedPaymentMethods: [String.t()] | nil,
          captureDelayHours: integer | nil,
          channel: String.t() | nil,
          company: Company.t() | nil,
          countryCode: String.t() | nil,
          dateOfBirth: Date.t() | nil,
          deliverAt: DateTime.t() | nil,
          deliveryAddress: DeliveryAddress.t() | nil,
          enableOneClick: boolean | nil,
          enablePayOut: boolean | nil,
          enableRecurring: boolean | nil,
          expiresAt: DateTime.t() | nil,
          fundOrigin: FundOrigin.t() | nil,
          fundRecipient: FundRecipient.t() | nil,
          installmentOptions: map | nil,
          lineItems: [LineItem.t()] | nil,
          mandate: Mandate.t() | nil,
          mcc: String.t() | nil,
          merchantAccount: String.t(),
          merchantOrderReference: String.t() | nil,
          metadata: map | nil,
          mode: String.t() | nil,
          mpiData: ThreeDSecureData.t() | nil,
          platformChargebackLogic: PlatformChargebackLogic.t() | nil,
          recurringExpiry: String.t() | nil,
          recurringFrequency: String.t() | nil,
          recurringProcessingModel: String.t() | nil,
          redirectFromIssuerMethod: String.t() | nil,
          redirectToIssuerMethod: String.t() | nil,
          reference: String.t(),
          returnUrl: String.t(),
          riskData: RiskData.t() | nil,
          shopperEmail: String.t() | nil,
          shopperIP: String.t() | nil,
          shopperInteraction: String.t() | nil,
          shopperLocale: String.t() | nil,
          shopperName: ShopperName.t() | nil,
          shopperReference: String.t() | nil,
          shopperStatement: String.t() | nil,
          showInstallmentAmount: boolean | nil,
          showRemovePaymentMethodButton: boolean | nil,
          socialSecurityNumber: String.t() | nil,
          splitCardFundingSources: boolean | nil,
          splits: [Split.t()] | nil,
          store: String.t() | nil,
          storeFiltrationMode: String.t() | nil,
          storePaymentMethod: boolean | nil,
          storePaymentMethodMode: String.t() | nil,
          telephoneNumber: String.t() | nil,
          themeId: String.t() | nil,
          threeDS2RequestData: CheckoutSessionThreeDs2RequestData.t() | nil,
          threeDSAuthenticationOnly: boolean | nil,
          trustedShopper: boolean | nil
        }

  defstruct [
    :accountInfo,
    :additionalAmount,
    :additionalData,
    :allowedPaymentMethods,
    :amount,
    :applicationInfo,
    :authenticationData,
    :billingAddress,
    :blockedPaymentMethods,
    :captureDelayHours,
    :channel,
    :company,
    :countryCode,
    :dateOfBirth,
    :deliverAt,
    :deliveryAddress,
    :enableOneClick,
    :enablePayOut,
    :enableRecurring,
    :expiresAt,
    :fundOrigin,
    :fundRecipient,
    :installmentOptions,
    :lineItems,
    :mandate,
    :mcc,
    :merchantAccount,
    :merchantOrderReference,
    :metadata,
    :mode,
    :mpiData,
    :platformChargebackLogic,
    :recurringExpiry,
    :recurringFrequency,
    :recurringProcessingModel,
    :redirectFromIssuerMethod,
    :redirectToIssuerMethod,
    :reference,
    :returnUrl,
    :riskData,
    :shopperEmail,
    :shopperIP,
    :shopperInteraction,
    :shopperLocale,
    :shopperName,
    :shopperReference,
    :shopperStatement,
    :showInstallmentAmount,
    :showRemovePaymentMethodButton,
    :socialSecurityNumber,
    :splitCardFundingSources,
    :splits,
    :store,
    :storeFiltrationMode,
    :storePaymentMethod,
    :storePaymentMethodMode,
    :telephoneNumber,
    :themeId,
    :threeDS2RequestData,
    :threeDSAuthenticationOnly,
    :trustedShopper
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accountInfo: {AccountInfo, :t},
      additionalAmount: {Amount, :t},
      additionalData: :map,
      allowedPaymentMethods: [:string],
      amount: {Amount, :t},
      applicationInfo: {ApplicationInfo, :t},
      authenticationData: {AuthenticationData, :t},
      billingAddress: {BillingAddress, :t},
      blockedPaymentMethods: [:string],
      captureDelayHours: {:integer, "int32"},
      channel: {:enum, ["iOS", "Android", "Web"]},
      company: {Company, :t},
      countryCode: :string,
      dateOfBirth: {:string, "date"},
      deliverAt: {:string, "date-time"},
      deliveryAddress: {DeliveryAddress, :t},
      enableOneClick: :boolean,
      enablePayOut: :boolean,
      enableRecurring: :boolean,
      expiresAt: {:string, "date-time"},
      fundOrigin: {FundOrigin, :t},
      fundRecipient: {FundRecipient, :t},
      installmentOptions: :map,
      lineItems: [{LineItem, :t}],
      mandate: {Mandate, :t},
      mcc: :string,
      merchantAccount: :string,
      merchantOrderReference: :string,
      metadata: :map,
      mode: {:enum, ["embedded", "hosted"]},
      mpiData: {ThreeDSecureData, :t},
      platformChargebackLogic: {PlatformChargebackLogic, :t},
      recurringExpiry: :string,
      recurringFrequency: :string,
      recurringProcessingModel: {:enum, ["CardOnFile", "Subscription", "UnscheduledCardOnFile"]},
      redirectFromIssuerMethod: :string,
      redirectToIssuerMethod: :string,
      reference: :string,
      returnUrl: :string,
      riskData: {RiskData, :t},
      shopperEmail: :string,
      shopperIP: :string,
      shopperInteraction: {:enum, ["Ecommerce", "ContAuth", "Moto", "POS"]},
      shopperLocale: :string,
      shopperName: {ShopperName, :t},
      shopperReference: :string,
      shopperStatement: :string,
      showInstallmentAmount: :boolean,
      showRemovePaymentMethodButton: :boolean,
      socialSecurityNumber: :string,
      splitCardFundingSources: :boolean,
      splits: [{Split, :t}],
      store: :string,
      storeFiltrationMode: {:enum, ["exclusive", "inclusive", "skipFilter"]},
      storePaymentMethod: :boolean,
      storePaymentMethodMode: {:enum, ["askForConsent", "disabled", "enabled"]},
      telephoneNumber: :string,
      themeId: :string,
      threeDS2RequestData: {CheckoutSessionThreeDs2RequestData, :t},
      threeDSAuthenticationOnly: :boolean,
      trustedShopper: :boolean
    ]
  end
end
