defmodule Adyen.Checkout.Donations do
  @moduledoc """
  Provides API endpoints related to donations
  """

  alias Adyen.Checkout.DonationCampaignsRequest
  alias Adyen.Checkout.DonationCampaignsResponse
  alias Adyen.Checkout.DonationPaymentRequest
  alias Adyen.Checkout.DonationPaymentResponse
  alias Adyen.Checkout.Donations
  alias Adyen.Checkout.ServiceError

  @default_client Adyen.Client

  @doc """
  Get a list of donation campaigns.

  Queries the available donation campaigns for a donation based on the donation context (like merchant account, currency, and locale). The response contains active donation campaigns.

  ## Request Body

  **Content Types**: `application/json`
  """
  @spec create_donation_campaigns(
          body :: DonationCampaignsRequest.t(),
          opts :: keyword
        ) ::
          {:ok, DonationCampaignsResponse.t()}
          | {:error, ServiceError.t()}
  def create_donation_campaigns(body, opts \\ []) do
    client = opts[:client] || @default_client

    client.request(%{
      args: [body: body],
      call: {Donations, :create_donation_campaigns},
      url: "/donationCampaigns",
      body: body,
      method: :post,
      request: [{"application/json", {DonationCampaignsRequest, :t}}],
      response: [
        {200, {DonationCampaignsResponse, :t}},
        {400, {ServiceError, :t}},
        {401, {ServiceError, :t}},
        {403, {ServiceError, :t}},
        {422, {ServiceError, :t}},
        {500, {ServiceError, :t}}
      ],
      opts: opts
    })
  end

  @doc """
  Make a donation

  Takes in the donation token generated by the `/payments` request and uses it to make the donation.

  For more information, see [Donations](https://docs.adyen.com/online-payments/donations).

  ## Request Body

  **Content Types**: `application/json`
  """
  @spec create_donation(body :: DonationPaymentRequest.t(), opts :: keyword) ::
          {:ok, DonationPaymentResponse.t()}
          | {:error, ServiceError.t()}
  def create_donation(body, opts \\ []) do
    client = opts[:client] || @default_client

    client.request(%{
      args: [body: body],
      call: {Donations, :create_donation},
      url: "/donations",
      body: body,
      method: :post,
      request: [{"application/json", {DonationPaymentRequest, :t}}],
      response: [
        {200, {DonationPaymentResponse, :t}},
        {400, {ServiceError, :t}},
        {401, {ServiceError, :t}},
        {403, {ServiceError, :t}},
        {422, {ServiceError, :t}},
        {500, {ServiceError, :t}}
      ],
      opts: opts
    })
  end
end
