defmodule Adyen.Management.V3.PaymentMethod do
  @moduledoc """
  Provides struct and type for a PaymentMethod
  """

  @type t :: %__MODULE__{
          accel: Adyen.Management.V3.AccelInfo.t() | nil,
          affirm: Adyen.Management.V3.AffirmInfo.t() | nil,
          afterpayTouch: Adyen.Management.V3.AfterpayTouchInfo.t() | nil,
          alipayPlus: Adyen.Management.V3.AlipayPlusInfo.t() | nil,
          allowed: boolean | nil,
          amex: Adyen.Management.V3.AmexInfo.t() | nil,
          applePay: Adyen.Management.V3.ApplePayInfo.t() | nil,
          bcmc: Adyen.Management.V3.BcmcInfo.t() | nil,
          businessLineId: String.t() | nil,
          cartesBancaires: Adyen.Management.V3.CartesBancairesInfo.t() | nil,
          clearpay: Adyen.Management.V3.ClearpayInfo.t() | nil,
          countries: [String.t()] | nil,
          cup: Adyen.Management.V3.GenericPmWithTdiInfo.t() | nil,
          currencies: [String.t()] | nil,
          customRoutingFlags: [String.t()] | nil,
          diners: Adyen.Management.V3.DinersInfo.t() | nil,
          discover: Adyen.Management.V3.GenericPmWithTdiInfo.t() | nil,
          eft_directdebit_CA: Adyen.Management.V3.GenericPmWithTdiInfo.t() | nil,
          eftpos_australia: Adyen.Management.V3.GenericPmWithTdiInfo.t() | nil,
          enabled: boolean | nil,
          girocard: Adyen.Management.V3.GenericPmWithTdiInfo.t() | nil,
          givex: Adyen.Management.V3.GivexInfo.t() | nil,
          googlePay: Adyen.Management.V3.GooglePayInfo.t() | nil,
          id: String.t(),
          ideal: Adyen.Management.V3.GenericPmWithTdiInfo.t() | nil,
          interac_card: Adyen.Management.V3.GenericPmWithTdiInfo.t() | nil,
          jcb: Adyen.Management.V3.JCBInfo.t() | nil,
          klarna: Adyen.Management.V3.KlarnaInfo.t() | nil,
          maestro: Adyen.Management.V3.GenericPmWithTdiInfo.t() | nil,
          maestro_usa: Adyen.Management.V3.GenericPmWithTdiInfo.t() | nil,
          mc: Adyen.Management.V3.GenericPmWithTdiInfo.t() | nil,
          mealVoucher_FR: Adyen.Management.V3.MealVoucherFRInfo.t() | nil,
          nyce: Adyen.Management.V3.NyceInfo.t() | nil,
          paybybank_plaid: Adyen.Management.V3.PayByBankPlaidInfo.t() | nil,
          payme: Adyen.Management.V3.PayMeInfo.t() | nil,
          paypal: Adyen.Management.V3.PayPalInfo.t() | nil,
          payto: Adyen.Management.V3.PayToInfo.t() | nil,
          pulse: Adyen.Management.V3.PulseInfo.t() | nil,
          reference: String.t() | nil,
          sepadirectdebit: Adyen.Management.V3.SepaDirectDebitInfo.t() | nil,
          shopperInteraction: String.t() | nil,
          sodexo: Adyen.Management.V3.SodexoInfo.t() | nil,
          sofort: Adyen.Management.V3.SofortInfo.t() | nil,
          star: Adyen.Management.V3.StarInfo.t() | nil,
          storeIds: [String.t()] | nil,
          svs: Adyen.Management.V3.SvsInfo.t() | nil,
          swish: Adyen.Management.V3.SwishInfo.t() | nil,
          ticket: Adyen.Management.V3.TicketInfo.t() | nil,
          twint: Adyen.Management.V3.TwintInfo.t() | nil,
          type: String.t() | nil,
          valuelink: Adyen.Management.V3.ValuelinkInfo.t() | nil,
          verificationStatus: String.t() | nil,
          vipps: Adyen.Management.V3.VippsInfo.t() | nil,
          visa: Adyen.Management.V3.GenericPmWithTdiInfo.t() | nil,
          wechatpay: Adyen.Management.V3.WeChatPayInfo.t() | nil,
          wechatpay_pos: Adyen.Management.V3.WeChatPayPosInfo.t() | nil
        }

  defstruct [
    :accel,
    :affirm,
    :afterpayTouch,
    :alipayPlus,
    :allowed,
    :amex,
    :applePay,
    :bcmc,
    :businessLineId,
    :cartesBancaires,
    :clearpay,
    :countries,
    :cup,
    :currencies,
    :customRoutingFlags,
    :diners,
    :discover,
    :eft_directdebit_CA,
    :eftpos_australia,
    :enabled,
    :girocard,
    :givex,
    :googlePay,
    :id,
    :ideal,
    :interac_card,
    :jcb,
    :klarna,
    :maestro,
    :maestro_usa,
    :mc,
    :mealVoucher_FR,
    :nyce,
    :paybybank_plaid,
    :payme,
    :paypal,
    :payto,
    :pulse,
    :reference,
    :sepadirectdebit,
    :shopperInteraction,
    :sodexo,
    :sofort,
    :star,
    :storeIds,
    :svs,
    :swish,
    :ticket,
    :twint,
    :type,
    :valuelink,
    :verificationStatus,
    :vipps,
    :visa,
    :wechatpay,
    :wechatpay_pos
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accel: {Adyen.Management.V3.AccelInfo, :t},
      affirm: {Adyen.Management.V3.AffirmInfo, :t},
      afterpayTouch: {Adyen.Management.V3.AfterpayTouchInfo, :t},
      alipayPlus: {Adyen.Management.V3.AlipayPlusInfo, :t},
      allowed: :boolean,
      amex: {Adyen.Management.V3.AmexInfo, :t},
      applePay: {Adyen.Management.V3.ApplePayInfo, :t},
      bcmc: {Adyen.Management.V3.BcmcInfo, :t},
      businessLineId: :string,
      cartesBancaires: {Adyen.Management.V3.CartesBancairesInfo, :t},
      clearpay: {Adyen.Management.V3.ClearpayInfo, :t},
      countries: [:string],
      cup: {Adyen.Management.V3.GenericPmWithTdiInfo, :t},
      currencies: [:string],
      customRoutingFlags: [:string],
      diners: {Adyen.Management.V3.DinersInfo, :t},
      discover: {Adyen.Management.V3.GenericPmWithTdiInfo, :t},
      eft_directdebit_CA: {Adyen.Management.V3.GenericPmWithTdiInfo, :t},
      eftpos_australia: {Adyen.Management.V3.GenericPmWithTdiInfo, :t},
      enabled: :boolean,
      girocard: {Adyen.Management.V3.GenericPmWithTdiInfo, :t},
      givex: {Adyen.Management.V3.GivexInfo, :t},
      googlePay: {Adyen.Management.V3.GooglePayInfo, :t},
      id: :string,
      ideal: {Adyen.Management.V3.GenericPmWithTdiInfo, :t},
      interac_card: {Adyen.Management.V3.GenericPmWithTdiInfo, :t},
      jcb: {Adyen.Management.V3.JCBInfo, :t},
      klarna: {Adyen.Management.V3.KlarnaInfo, :t},
      maestro: {Adyen.Management.V3.GenericPmWithTdiInfo, :t},
      maestro_usa: {Adyen.Management.V3.GenericPmWithTdiInfo, :t},
      mc: {Adyen.Management.V3.GenericPmWithTdiInfo, :t},
      mealVoucher_FR: {Adyen.Management.V3.MealVoucherFRInfo, :t},
      nyce: {Adyen.Management.V3.NyceInfo, :t},
      paybybank_plaid: {Adyen.Management.V3.PayByBankPlaidInfo, :t},
      payme: {Adyen.Management.V3.PayMeInfo, :t},
      paypal: {Adyen.Management.V3.PayPalInfo, :t},
      payto: {Adyen.Management.V3.PayToInfo, :t},
      pulse: {Adyen.Management.V3.PulseInfo, :t},
      reference: :string,
      sepadirectdebit: {Adyen.Management.V3.SepaDirectDebitInfo, :t},
      shopperInteraction: :string,
      sodexo: {Adyen.Management.V3.SodexoInfo, :t},
      sofort: {Adyen.Management.V3.SofortInfo, :t},
      star: {Adyen.Management.V3.StarInfo, :t},
      storeIds: [:string],
      svs: {Adyen.Management.V3.SvsInfo, :t},
      swish: {Adyen.Management.V3.SwishInfo, :t},
      ticket: {Adyen.Management.V3.TicketInfo, :t},
      twint: {Adyen.Management.V3.TwintInfo, :t},
      type: :string,
      valuelink: {Adyen.Management.V3.ValuelinkInfo, :t},
      verificationStatus: {:enum, ["valid", "pending", "invalid", "rejected"]},
      vipps: {Adyen.Management.V3.VippsInfo, :t},
      visa: {Adyen.Management.V3.GenericPmWithTdiInfo, :t},
      wechatpay: {Adyen.Management.V3.WeChatPayInfo, :t},
      wechatpay_pos: {Adyen.Management.V3.WeChatPayPosInfo, :t}
    ]
  end
end
