defmodule Adyen.Transfers.TransferData do
  @moduledoc """
  Provides struct and type for a TransferData
  """

  alias Adyen.Transfers.Amount
  alias Adyen.Transfers.BalanceMutation
  alias Adyen.Transfers.BankCategoryData
  alias Adyen.Transfers.ConfirmationTrackingData
  alias Adyen.Transfers.DirectDebitInformation
  alias Adyen.Transfers.EstimationTrackingData
  alias Adyen.Transfers.ExecutionDate
  alias Adyen.Transfers.ExternalReason
  alias Adyen.Transfers.InternalCategoryData
  alias Adyen.Transfers.InternalReviewTrackingData
  alias Adyen.Transfers.IssuedCard
  alias Adyen.Transfers.PaymentInstrument
  alias Adyen.Transfers.PlatformPayment
  alias Adyen.Transfers.ResourceReference
  alias Adyen.Transfers.TransactionRulesResult
  alias Adyen.Transfers.TransferEvent
  alias Adyen.Transfers.TransferNotificationCounterParty
  alias Adyen.Transfers.TransferReview

  @type t :: %__MODULE__{
          accountHolder: ResourceReference.t() | nil,
          amount: Amount.t(),
          balanceAccount: ResourceReference.t() | nil,
          balancePlatform: String.t() | nil,
          balances: [BalanceMutation.t()] | nil,
          category: String.t(),
          categoryData:
            BankCategoryData.t()
            | InternalCategoryData.t()
            | IssuedCard.t()
            | PlatformPayment.t()
            | nil,
          counterparty: TransferNotificationCounterParty.t() | nil,
          createdAt: DateTime.t() | nil,
          creationDate: DateTime.t() | nil,
          description: String.t() | nil,
          directDebitInformation: DirectDebitInformation.t() | nil,
          direction: String.t() | nil,
          eventId: String.t() | nil,
          events: [TransferEvent.t()] | nil,
          executionDate: ExecutionDate.t() | nil,
          externalReason: ExternalReason.t() | nil,
          id: String.t() | nil,
          paymentInstrument: PaymentInstrument.t() | nil,
          reason: String.t() | nil,
          reference: String.t() | nil,
          referenceForBeneficiary: String.t() | nil,
          review: TransferReview.t() | nil,
          sequenceNumber: integer | nil,
          status: String.t(),
          tracking:
            ConfirmationTrackingData.t()
            | EstimationTrackingData.t()
            | InternalReviewTrackingData.t()
            | nil,
          transactionRulesResult: TransactionRulesResult.t() | nil,
          type: String.t() | nil,
          updatedAt: DateTime.t() | nil
        }

  defstruct [
    :accountHolder,
    :amount,
    :balanceAccount,
    :balancePlatform,
    :balances,
    :category,
    :categoryData,
    :counterparty,
    :createdAt,
    :creationDate,
    :description,
    :directDebitInformation,
    :direction,
    :eventId,
    :events,
    :executionDate,
    :externalReason,
    :id,
    :paymentInstrument,
    :reason,
    :reference,
    :referenceForBeneficiary,
    :review,
    :sequenceNumber,
    :status,
    :tracking,
    :transactionRulesResult,
    :type,
    :updatedAt
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      accountHolder: {ResourceReference, :t},
      amount: {Amount, :t},
      balanceAccount: {ResourceReference, :t},
      balancePlatform: :string,
      balances: [{BalanceMutation, :t}],
      category: {:enum, ["bank", "card", "internal", "issuedCard", "platformPayment", "topUp"]},
      categoryData:
        {:union,
         [
           {BankCategoryData, :t},
           {InternalCategoryData, :t},
           {IssuedCard, :t},
           {PlatformPayment, :t}
         ]},
      counterparty: {TransferNotificationCounterParty, :t},
      createdAt: {:string, "date-time"},
      creationDate: {:string, "date-time"},
      description: :string,
      directDebitInformation: {DirectDebitInformation, :t},
      direction: {:enum, ["incoming", "outgoing"]},
      eventId: :string,
      events: [{TransferEvent, :t}],
      executionDate: {ExecutionDate, :t},
      externalReason: {ExternalReason, :t},
      id: :string,
      paymentInstrument: {PaymentInstrument, :t},
      reason:
        {:enum,
         [
           "accountHierarchyNotActive",
           "amountLimitExceeded",
           "approvalExpired",
           "approved",
           "avsDeclined",
           "balanceAccountTemporarilyBlockedByTransactionRule",
           "blockCard",
           "callReferral",
           "cancelled",
           "captureCard",
           "cardExpired",
           "cardholderAuthenticationRequired",
           "cashbackAmountExceedsLimit",
           "cavvDeclined",
           "contactlessFallback",
           "contactlessLimitReached",
           "counterpartyAccountBlocked",
           "counterpartyAccountClosed",
           "counterpartyAccountNotFound",
           "counterpartyAddressRequired",
           "counterpartyBankTimedOut",
           "counterpartyBankUnavailable",
           "cryptographicFailure",
           "cvcDeclined",
           "declined",
           "declinedByBapValidation",
           "declinedByTransactionRule",
           "declinedNonGeneric",
           "directDebitNotSupported",
           "doNotHonor",
           "domesticDebitTransactionNotAllowed",
           "duplicateTransmissionDetected",
           "error",
           "formatError",
           "fraud",
           "fraudCancelled",
           "honorWithId",
           "internalTimeout",
           "invalidAccount",
           "invalidAmount",
           "invalidAuthorizationLifeCycle",
           "invalidCard",
           "invalidExpiryDate",
           "invalidFromAccount",
           "invalidIssuer",
           "invalidMerchant",
           "invalidPin",
           "invalidToAccount",
           "invalidTransaction",
           "issuerSuspectedFraud",
           "lostCard",
           "mobilePinRequired",
           "noCheckingAccount",
           "noSavingsAccount",
           "not3dAuthenticated",
           "notEnoughBalance",
           "notSubmitted",
           "notSupported",
           "partiallyApproved",
           "pending",
           "pendingApproval",
           "pendingExecution",
           "pinNotChanged",
           "pinRequired",
           "pinTriesExceeded",
           "pinValidationNotPossible",
           "purchaseAmountOnlyNoCashBack",
           "refusedByCounterpartyBank",
           "refusedByCustomer",
           "restrictedCard",
           "revocationOfAuth",
           "routeNotFound",
           "scaAuthenticationRequired",
           "scaFailed",
           "schemeAdvice",
           "securityViolation",
           "shopperCancelled",
           "stolenCard",
           "threedsDynamicLinkingMismatch",
           "transactionNotPermitted",
           "transferInstrumentDoesNotExist",
           "unableToRouteTransaction",
           "unknown",
           "withdrawalAmountExceeded",
           "withdrawalCountExceeded"
         ]},
      reference: :string,
      referenceForBeneficiary: :string,
      review: {TransferReview, :t},
      sequenceNumber: {:integer, "int32"},
      status:
        {:enum,
         [
           "approvalPending",
           "atmWithdrawal",
           "atmWithdrawalReversalPending",
           "atmWithdrawalReversed",
           "authAdjustmentAuthorised",
           "authAdjustmentError",
           "authAdjustmentRefused",
           "authorised",
           "bankTransfer",
           "bankTransferPending",
           "booked",
           "bookingPending",
           "cancelled",
           "capturePending",
           "captureReversalPending",
           "captureReversed",
           "captured",
           "capturedExternally",
           "chargeback",
           "chargebackExternally",
           "chargebackPending",
           "chargebackReversalPending",
           "chargebackReversed",
           "credited",
           "depositCorrection",
           "depositCorrectionPending",
           "dispute",
           "disputeClosed",
           "disputeExpired",
           "disputeNeedsReview",
           "error",
           "expired",
           "failed",
           "fee",
           "feePending",
           "internalTransfer",
           "internalTransferPending",
           "invoiceDeduction",
           "invoiceDeductionPending",
           "manualCorrectionPending",
           "manuallyCorrected",
           "matchedStatement",
           "matchedStatementPending",
           "merchantPayin",
           "merchantPayinPending",
           "merchantPayinReversed",
           "merchantPayinReversedPending",
           "miscCost",
           "miscCostPending",
           "paymentCost",
           "paymentCostPending",
           "pendingApproval",
           "pendingExecution",
           "received",
           "refundPending",
           "refundReversalPending",
           "refundReversed",
           "refunded",
           "refundedExternally",
           "refused",
           "rejected",
           "reserveAdjustment",
           "reserveAdjustmentPending",
           "returned",
           "secondChargeback",
           "secondChargebackPending",
           "undefined"
         ]},
      tracking:
        {:union,
         [
           {ConfirmationTrackingData, :t},
           {EstimationTrackingData, :t},
           {InternalReviewTrackingData, :t}
         ]},
      transactionRulesResult: {TransactionRulesResult, :t},
      type:
        {:enum,
         [
           "payment",
           "capture",
           "captureReversal",
           "refund",
           "refundReversal",
           "chargeback",
           "chargebackCorrection",
           "chargebackReversal",
           "chargebackReversalCorrection",
           "secondChargeback",
           "secondChargebackCorrection",
           "atmWithdrawal",
           "atmWithdrawalReversal",
           "internalTransfer",
           "internalDirectDebit",
           "manualCorrection",
           "invoiceDeduction",
           "depositCorrection",
           "reserveAdjustment",
           "bankTransfer",
           "bankDirectDebit",
           "cardTransfer",
           "miscCost",
           "paymentCost",
           "fee",
           "leftover",
           "grant",
           "capitalFundsCollection",
           "cashOutInstruction",
           "cashoutFee",
           "cashoutRepayment",
           "cashoutFunding",
           "repayment",
           "installment",
           "installmentReversal",
           "balanceAdjustment",
           "balanceRollover",
           "balanceMigration"
         ]},
      updatedAt: {:string, "date-time"}
    ]
  end
end
